services:
  mysql:
    image: docker.io/mysql:8.2.0
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - test-vol:/var/lib/mysql
volumes:
  test-vol:
    external: true
